# Generated by Django 4.0.1 on 2022-01-14 04:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Телефон'),
        ),
    ]
